#!/bin/bash
DESTDIR="/Work/Packages"
SOURCEDIR="/Work/Source"
PKGSDIR="/Work/tars"
source confile
echo 2>/tmp/build_logs
echo "Compiling $Name..."
tar -xf $PKGSDIR/$Sourcefile -C $SOURCEDIR
cd $SOURCEDIR
if [[ -d $DESTDIR/$Group/$Name ]] ; then
	rm -rf $DESTDIR/$Group/$Name
fi
makeit $DESTDIR/$Group/"$Name"

if [[ $? != 0 ]] ; then
	touch "/tmp/failed"
else
	touch "/tmp/passed"
fi

cd $DESTDIR/$Group/"$Name"
Size=$( du -hs | cut -f1)
Date=$( date )
mkdir info
echo "Name: $Name" >> info/info
echo "Version: $Version" >> info/info
echo "Description: $Description" >> info/info
echo "Size: $Size" >> info/info
echo "Date: $Date" >> info/info
echo "Packager: Manjeet Singh" >> info/info

find . -type f >> info/list

for i in $(find . -type f) ; do
	sha512sum $i >> info/hashs
done