#!/bin/sh

# =============================================================================
# confile nothing but a simple file which contains information about packages
# information about how to compile it 
# simple and straight forward

mkdir $1-$2	# make folder for clean development with arguments $1 = Name && $2 = Version
cd $1-$2		
				
cat > confile << "EOF"
Name=
Version=
Description=" "
License=" "
Source=" "


compileit() {
# compilation command
#./configure --prefix=/usr --disable-static
# make -j4 
# make install DESTDIR=$1
return $?

}
## write description here
EOF
nano confile
