#!/bin/sh
mkdir $1-$2
cd $1-$2
if [[ ! -s confile ]] ; then
cat > confile << "EOF"
Name=$1
Version=$2
Description=" "
License=" "
Source=" "


compileit() {
./configure --prefix=/usr --disable-static
make -j4 
make install DESTDIR=$1
return $?

}
EOF
fi
nano confile